services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: visittrack.local,www.visittrack.local
      LETSENCRYPT_HOST: visittrack.local,www.visittrack.local
      LETSENCRYPT_EMAIL: edujudici@gmail.com
    tty: true
    stdin_open: true
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy
    external: true
